### ISSUE TITLE
[feature] Manually specify command

### ISSUE THREAD

**Issue by dkasak** [Ayrx/atriage#1]
It seems that a lot of this command isn't really specific to afl and could be useful for general crash triage. It would be nice if there was a command/switch that would allow you to manually specify the command to be run and an (arbitrary) directory containing the samples.

**Comment by Ayrx** [comment]
Hi,

Yes! I designed `atriage` to be extensible. I just have not gotten around to implementing any other collectors other than afl-fuzz yet since I did not have a immediate need for it.

Since there is now a feature request I'll try to put aside some time to implement it. :)

**Comment by Ayrx** [comment]
I have added support for collecting files from a flat (no subdirectories) directory containing crash samples in 1f800a1.

While it defaults to collecting for afl, you can use `atriage triage --collector` to choose a specific collector (`atriage list-collectors` to get a list of supported collectors). The `atriage triage --command` option can be used to set an arbitrary command.

I'll test it out for a few more days to iron out any potential bugs before cutting a release. I'll close this issue when the feature makes it to a PyPI release. :)

**Comment by dkasak** [comment]
Looks great! I'll test it out shortly.

**Comment by Ayrx** [comment]
@dkasak Did you get a chance to test the feature? If you don't spot any bugs I'll make a release in the next day or so. :)

**Comment by Ayrx** [comment]
I have made a 0.3 release with this feature. Do let me know if you find any bugs. :)

**Comment by dkasak** [comment]
Sorry, a bit busy at the moment. It appears to work well, will let you know if I find something.
